// Site Configuration
export const siteConfig = {
  name: 'Amr Gharib',
  title: 'Amr Gharib - Full Stack Developer & Tech Educator',
  description: 'World-class programmer, educator, and entrepreneur. Specializing in cutting-edge technologies, AI/ML, blockchain, and cloud architecture. Transform your ideas into reality.',
  url: 'https://gharib.dev',
  ogImage: 'https://gharib.dev/og.jpg',
  email: 'amr@gharib.dev',
  phone: '+201500650001',
  location: 'Cairo, Egypt',
  social: {
    github: 'https://www.gharib.dev',
    linkedin: 'https://www.gharib.dev',
    twitter: 'https://www.gharib.dev',
    youtube: 'https://www.gharib.dev',
    instagram: 'https://www.gharib.dev',
    facebook: 'https://www.gharib.dev',
    discord: 'https://www.gharib.dev',
  },
}

// Navigation
export const navigation = [
  { name: 'Home', href: '/' },
  { name: 'About', href: '/about' },
  { name: 'Portfolio', href: '/portfolio' },
  { name: 'Services', href: '/services' },
  { name: 'Courses', href: '/courses' },
  { name: 'Blog', href: '/blog' },
  { name: 'Appointments', href: '/appointments' },
  { name: 'Contact', href: '/contact' },
]

// Skills
export const skills = {
  languages: [
    { name: 'JavaScript/TypeScript', level: 98 },
    { name: 'Python', level: 96 },
    { name: 'C/C++', level: 94 },
    { name: 'Rust', level: 90 },
    { name: 'Go', level: 92 },
    { name: 'Java/Kotlin', level: 91 },
    { name: 'Swift', level: 88 },
    { name: 'C#', level: 93 },
    { name: 'PHP', level: 89 },
    { name: 'Ruby', level: 85 },
    { name: 'Solidity', level: 87 },
    { name: 'Assembly', level: 80 },
  ],
  frontend: [
    { name: 'React/Next.js', level: 99 },
    { name: 'Vue/Nuxt.js', level: 95 },
    { name: 'Angular', level: 92 },
    { name: 'Svelte/SvelteKit', level: 90 },
    { name: 'Three.js/WebGL', level: 93 },
    { name: 'React Native', level: 94 },
    { name: 'Flutter', level: 91 },
    { name: 'Tailwind CSS', level: 99 },
    { name: 'GSAP/Framer Motion', level: 96 },
    { name: 'WebXR/AR.js', level: 85 },
  ],
  backend: [
    { name: 'Node.js/Express', level: 98 },
    { name: 'Django/FastAPI', level: 95 },
    { name: 'Spring Boot', level: 90 },
    { name: 'ASP.NET Core', level: 91 },
    { name: 'Ruby on Rails', level: 87 },
    { name: 'GraphQL', level: 94 },
    { name: 'gRPC', level: 89 },
    { name: 'Microservices', level: 96 },
    { name: 'Serverless', level: 95 },
    { name: 'WebSockets', level: 93 },
  ],
  database: [
    { name: 'PostgreSQL', level: 97 },
    { name: 'MongoDB', level: 95 },
    { name: 'Redis', level: 94 },
    { name: 'MySQL', level: 93 },
    { name: 'Elasticsearch', level: 90 },
    { name: 'Cassandra', level: 86 },
    { name: 'Neo4j', level: 84 },
    { name: 'Firebase/Supabase', level: 95 },
  ],
  devops: [
    { name: 'Docker', level: 97 },
    { name: 'Kubernetes', level: 94 },
    { name: 'AWS', level: 96 },
    { name: 'GCP', level: 93 },
    { name: 'Azure', level: 91 },
    { name: 'Terraform', level: 90 },
    { name: 'CI/CD', level: 95 },
    { name: 'Linux/Bash', level: 97 },
  ],
  ai_ml: [
    { name: 'TensorFlow/PyTorch', level: 93 },
    { name: 'Machine Learning', level: 91 },
    { name: 'Deep Learning', level: 90 },
    { name: 'NLP/LLMs', level: 92 },
    { name: 'Computer Vision', level: 88 },
    { name: 'MLOps', level: 87 },
    { name: 'OpenAI/LangChain', level: 94 },
  ],
  other: [
    { name: 'System Design', level: 96 },
    { name: 'Cybersecurity', level: 91 },
    { name: 'Blockchain/Web3', level: 89 },
    { name: 'IoT/Embedded', level: 85 },
    { name: 'Game Development', level: 84 },
    { name: 'Technical Writing', level: 93 },
    { name: 'Public Speaking', level: 95 },
    { name: 'Team Leadership', level: 96 },
  ],
}

// Personal Info
export const personalInfo = {
  birthDate: '1998-05-20',
  age: 27,
  yearsOfExperience: 18, // Started at 9 years old (2007)
  startedCodingAge: 9,
  startedCodingYear: 2007,
}

// Timeline
export const timeline = [
  {
    year: '2007',
    title: 'The Beginning',
    description: 'Started learning programming at age 9, creating simple games and scripts. The passion for technology was ignited.',
    icon: 'rocket',
  },
  {
    year: '2010',
    title: 'First Web Projects',
    description: 'Built first websites and web applications at age 12. Learned HTML, CSS, JavaScript, and PHP.',
    icon: 'globe',
  },
  {
    year: '2014',
    title: 'Advanced Development',
    description: 'Mastered multiple programming languages and frameworks at 16. Started freelancing and building complex applications.',
    icon: 'code',
  },
  {
    year: '2016',
    title: 'University Studies',
    description: 'Enrolled at The American University in Cairo for MICT and Computer Engineering dual degree at 18.',
    icon: 'graduation-cap',
  },
  {
    year: '2018',
    title: 'Enterprise Experience',
    description: 'Worked with Fortune 500 companies on large-scale distributed systems and cloud architecture.',
    icon: 'building',
  },
  {
    year: '2020',
    title: 'AI & Machine Learning',
    description: 'Deep dive into artificial intelligence, machine learning, and data science. Built AI-powered applications.',
    icon: 'brain',
  },
  {
    year: '2022',
    title: 'Teaching & Mentoring',
    description: 'Started teaching programming and business. Mentored hundreds of aspiring developers worldwide.',
    icon: 'users',
  },
  {
    year: '2024',
    title: 'Tech Leadership',
    description: 'Leading innovative projects, consulting for startups, and pushing technological boundaries at 26.',
    icon: 'link',
  },
  {
    year: '2025',
    title: 'Innovation Pioneer',
    description: 'At 27, pioneering next-gen AI solutions, Web3 applications, and mentoring the next generation of developers.',
    icon: 'star',
  },
]

// Services
export const services = [
  {
    id: 'web-development',
    title: 'Full Stack Web Development',
    description: 'End-to-end web application development with modern frameworks, scalable architecture, and stunning UI/UX.',
    icon: 'monitor',
    features: [
      'Custom web applications',
      'E-commerce platforms',
      'SaaS products',
      'Progressive Web Apps',
      'API development',
      'Database design',
    ],
    price: 'From $5,000',
  },
  {
    id: 'mobile-development',
    title: 'Mobile App Development',
    description: 'Native and cross-platform mobile applications for iOS and Android with exceptional performance.',
    icon: 'smartphone',
    features: [
      'React Native apps',
      'Flutter apps',
      'Native iOS (Swift)',
      'Native Android (Kotlin)',
      'App Store deployment',
      'Push notifications',
    ],
    price: 'From $8,000',
  },
  {
    id: 'ai-solutions',
    title: 'AI & Machine Learning Solutions',
    description: 'Intelligent systems, predictive analytics, and AI-powered automation for your business.',
    icon: 'brain',
    features: [
      'Custom AI models',
      'Natural language processing',
      'Computer vision',
      'Chatbots & assistants',
      'Predictive analytics',
      'MLOps & deployment',
    ],
    price: 'From $10,000',
  },
  {
    id: 'cloud-architecture',
    title: 'Cloud & DevOps',
    description: 'Scalable cloud infrastructure, containerization, and automated deployment pipelines.',
    icon: 'cloud',
    features: [
      'AWS/GCP/Azure setup',
      'Kubernetes orchestration',
      'CI/CD pipelines',
      'Infrastructure as Code',
      'Performance optimization',
      '24/7 monitoring',
    ],
    price: 'From $3,000',
  },
  {
    id: 'consulting',
    title: 'Technical Consulting',
    description: 'Strategic technology guidance, architecture reviews, and digital transformation consulting.',
    icon: 'lightbulb',
    features: [
      'Architecture review',
      'Technology strategy',
      'Code audits',
      'Security assessment',
      'Performance analysis',
      'Team training',
    ],
    price: 'From $200/hour',
  },
  {
    id: 'training',
    title: 'Training & Workshops',
    description: 'Comprehensive training programs for individuals and teams on cutting-edge technologies.',
    icon: 'presentation',
    features: [
      'Custom curriculum',
      'Hands-on workshops',
      '1-on-1 mentoring',
      'Corporate training',
      'Certification prep',
      'Career guidance',
    ],
    price: 'From $150/hour',
  },
]

// Courses
export const courses = [
  {
    id: 'full-stack-mastery',
    title: 'Full Stack Development Mastery',
    slug: 'full-stack-mastery',
    description: 'Complete guide to becoming a professional full stack developer with React, Node.js, and cloud deployment.',
    longDescription: 'This comprehensive course takes you from zero to hero in full stack development. You will learn front-end development with React and Next.js, back-end with Node.js and Express, database management, authentication, deployment, and best practices used by top tech companies.',
    image: '/courses/fullstack.jpg',
    price: 299,
    originalPrice: 599,
    duration: '40 hours',
    level: 'Intermediate',
    category: 'Web Development',
    students: 2847,
    rating: 4.9,
    lessons: 120,
    isFeatured: true,
  },
  {
    id: 'ai-ml-bootcamp',
    title: 'AI & Machine Learning Bootcamp',
    slug: 'ai-ml-bootcamp',
    description: 'Master artificial intelligence and machine learning from fundamentals to advanced deep learning.',
    longDescription: 'Dive deep into the world of AI and machine learning. This bootcamp covers Python for data science, machine learning algorithms, neural networks, natural language processing, computer vision, and deploying ML models in production.',
    image: '/courses/aiml.jpg',
    price: 399,
    originalPrice: 799,
    duration: '60 hours',
    level: 'Intermediate to Advanced',
    category: 'AI & ML',
    students: 1923,
    rating: 4.8,
    lessons: 180,
    isFeatured: true,
  },
  {
    id: 'system-design',
    title: 'System Design for Interviews & Real World',
    slug: 'system-design',
    description: 'Learn to design scalable systems like Netflix, Uber, and Twitter. Perfect for interviews and real projects.',
    longDescription: 'Master the art of system design with real-world examples. Learn about distributed systems, microservices, caching, load balancing, database sharding, message queues, and how to design systems that handle millions of users.',
    image: '/courses/system-design.jpg',
    price: 199,
    originalPrice: 399,
    duration: '25 hours',
    level: 'Advanced',
    category: 'Architecture',
    students: 3421,
    rating: 4.9,
    lessons: 75,
    isFeatured: true,
  },
  {
    id: 'react-native-pro',
    title: 'React Native: Build Production Apps',
    slug: 'react-native-pro',
    description: 'Build professional mobile apps for iOS and Android using React Native and Expo.',
    longDescription: 'Create beautiful, performant mobile applications with React Native. This course covers navigation, state management, native modules, animations, push notifications, and publishing to app stores.',
    image: '/courses/react-native.jpg',
    price: 249,
    originalPrice: 499,
    duration: '35 hours',
    level: 'Intermediate',
    category: 'Mobile Development',
    students: 1654,
    rating: 4.7,
    lessons: 100,
    isFeatured: false,
  },
  {
    id: 'web3-blockchain',
    title: 'Web3 & Blockchain Development',
    slug: 'web3-blockchain',
    description: 'Enter the decentralized world. Build DApps, smart contracts, and DeFi applications.',
    longDescription: 'Learn blockchain technology from the ground up. This course covers Ethereum, Solidity, smart contracts, Web3.js, DeFi protocols, NFTs, and building full decentralized applications.',
    image: '/courses/web3.jpg',
    price: 349,
    originalPrice: 699,
    duration: '45 hours',
    level: 'Intermediate',
    category: 'Blockchain',
    students: 1287,
    rating: 4.8,
    lessons: 130,
    isFeatured: false,
  },
  {
    id: 'cybersecurity-essentials',
    title: 'Cybersecurity Essentials',
    slug: 'cybersecurity-essentials',
    description: 'Protect applications and infrastructure. Learn ethical hacking and security best practices.',
    longDescription: 'Comprehensive cybersecurity training covering network security, web application security, penetration testing, cryptography, secure coding practices, and compliance frameworks.',
    image: '/courses/security.jpg',
    price: 279,
    originalPrice: 559,
    duration: '30 hours',
    level: 'Intermediate',
    category: 'Security',
    students: 2156,
    rating: 4.8,
    lessons: 90,
    isFeatured: false,
  },
  {
    id: 'devops-cloud',
    title: 'DevOps & Cloud Mastery',
    slug: 'devops-cloud',
    description: 'Master Docker, Kubernetes, AWS, and CI/CD pipelines for modern deployment workflows.',
    longDescription: 'Become a DevOps engineer with this comprehensive course. Learn containerization, orchestration, cloud platforms, infrastructure as code, monitoring, and building robust deployment pipelines.',
    image: '/courses/devops.jpg',
    price: 299,
    originalPrice: 599,
    duration: '40 hours',
    level: 'Intermediate to Advanced',
    category: 'DevOps',
    students: 1832,
    rating: 4.9,
    lessons: 110,
    isFeatured: false,
  },
  {
    id: 'startup-tech',
    title: 'Tech Entrepreneurship',
    slug: 'startup-tech',
    description: 'Build and scale tech startups. From MVP to funding and beyond.',
    longDescription: 'Learn the technical and business aspects of building a successful tech startup. Covers ideation, MVP development, product-market fit, fundraising, scaling, and managing technical teams.',
    image: '/courses/startup.jpg',
    price: 199,
    originalPrice: 399,
    duration: '20 hours',
    level: 'All Levels',
    category: 'Business',
    students: 987,
    rating: 4.7,
    lessons: 60,
    isFeatured: false,
  },
]

// Projects
export const projects = [
  {
    id: 'nexus-platform',
    title: 'Nexus Enterprise Platform',
    slug: 'nexus-platform',
    description: 'A comprehensive enterprise resource planning system handling 50M+ daily transactions for Fortune 500 companies.',
    image: '/projects/nexus.jpg',
    technologies: ['React', 'Node.js', 'PostgreSQL', 'Kubernetes', 'AWS'],
    category: 'Enterprise',
    client: 'Fortune 500 Client',
    featured: true,
    liveUrl: 'https://nexus-demo.gharib.dev',
    githubUrl: 'https://github.com/xgharibx/nexus-platform',
  },
  {
    id: 'aurora-ai',
    title: 'Aurora AI Assistant',
    slug: 'aurora-ai',
    description: 'An advanced AI-powered virtual assistant with natural language processing and multi-modal capabilities.',
    image: '/projects/aurora.jpg',
    technologies: ['Python', 'TensorFlow', 'FastAPI', 'React', 'WebRTC'],
    category: 'AI/ML',
    client: 'Tech Startup',
    featured: true,
    liveUrl: 'https://aurora-demo.gharib.dev',
    githubUrl: 'https://github.com/xgharibx/aurora-ai',
  },
  {
    id: 'defi-protocol',
    title: 'Quantum DeFi Protocol',
    slug: 'defi-protocol',
    description: 'Decentralized finance protocol with automated market making and yield optimization.',
    image: '/projects/defi.jpg',
    technologies: ['Solidity', 'Hardhat', 'React', 'Web3.js', 'TheGraph'],
    category: 'Blockchain',
    client: 'Crypto DAO',
    featured: true,
    liveUrl: 'https://defi-demo.gharib.dev',
    githubUrl: 'https://github.com/xgharibx/quantum-defi',
  },
  {
    id: 'pulse-health',
    title: 'Pulse Health Platform',
    slug: 'pulse-health',
    description: 'Telemedicine platform connecting millions of patients with healthcare providers worldwide.',
    image: '/projects/health.jpg',
    technologies: ['Next.js', 'Django', 'PostgreSQL', 'WebRTC', 'GCP'],
    category: 'Healthcare',
    client: 'Healthcare Network',
    featured: true,
    liveUrl: 'https://pulse-demo.gharib.dev',
    githubUrl: 'https://github.com/xgharibx/pulse-health',
  },
  {
    id: 'velocity-ecommerce',
    title: 'Velocity E-Commerce',
    slug: 'velocity-ecommerce',
    description: 'High-performance e-commerce platform processing $100M+ annual transactions with sub-100ms response times.',
    image: '/projects/ecommerce.jpg',
    technologies: ['Next.js', 'GraphQL', 'Redis', 'Stripe', 'Elasticsearch'],
    category: 'E-Commerce',
    client: 'Retail Giant',
    featured: false,
    liveUrl: 'https://velocity-demo.gharib.dev',
    githubUrl: 'https://github.com/xgharibx/velocity-ecommerce',
  },
  {
    id: 'smart-city',
    title: 'Smart City IoT Network',
    slug: 'smart-city',
    description: 'IoT infrastructure managing 10,000+ sensors for smart city traffic and environment monitoring.',
    image: '/projects/iot.jpg',
    technologies: ['Go', 'MQTT', 'InfluxDB', 'Grafana', 'Raspberry Pi'],
    category: 'IoT',
    client: 'Government Project',
    featured: false,
    liveUrl: 'https://smartcity-demo.gharib.dev',
    githubUrl: 'https://github.com/xgharibx/smart-city',
  },
  {
    id: 'gameverse',
    title: 'GameVerse MMO Engine',
    slug: 'gameverse',
    description: 'Custom multiplayer game engine supporting 100K concurrent players with real-time physics simulation.',
    image: '/projects/game.jpg',
    technologies: ['C++', 'Rust', 'Vulkan', 'Redis', 'Kafka'],
    category: 'Gaming',
    client: 'Game Studio',
    featured: false,
    liveUrl: 'https://gameverse-demo.gharib.dev',
    githubUrl: 'https://github.com/xgharibx/gameverse',
  },
  {
    id: 'fintech-app',
    title: 'NeoBank Mobile App',
    slug: 'fintech-app',
    description: 'Mobile banking application with real-time transactions, budgeting, and investment features.',
    image: '/projects/fintech.jpg',
    technologies: ['React Native', 'Node.js', 'MongoDB', 'Plaid', 'Stripe'],
    category: 'Fintech',
    client: 'Fintech Startup',
    featured: false,
    liveUrl: 'https://neobank-demo.gharib.dev',
    githubUrl: 'https://github.com/xgharibx/neobank',
  },
]

// Testimonials
export const testimonials = [
  {
    id: 1,
    name: 'Sarah Chen',
    role: 'CTO',
    company: 'TechVentures Inc.',
    image: '/testimonials/sarah.jpg',
    content: 'Amr is one of the most talented engineers I have ever worked with. His ability to architect complex systems while keeping code maintainable is exceptional. He transformed our entire infrastructure.',
    rating: 5,
  },
  {
    id: 2,
    name: 'Michael Roberts',
    role: 'Founder & CEO',
    company: 'StartupXYZ',
    image: '/testimonials/michael.jpg',
    content: 'Working with Amr was a game-changer for our startup. He built our MVP in record time and it scaled seamlessly to millions of users. His technical expertise is unmatched.',
    rating: 5,
  },
  {
    id: 3,
    name: 'Emily Watson',
    role: 'Engineering Manager',
    company: 'Global Tech Corp',
    image: '/testimonials/emily.jpg',
    content: 'Amr\'s training sessions elevated our entire engineering team. His teaching style is clear, engaging, and practical. We saw immediate improvements in code quality and productivity.',
    rating: 5,
  },
  {
    id: 4,
    name: 'Ahmed Hassan',
    role: 'Product Director',
    company: 'InnovateMENA',
    image: '/testimonials/ahmed.jpg',
    content: 'Exceptional work on our AI platform. Amr understood our vision perfectly and delivered beyond expectations. His AI/ML expertise is world-class.',
    rating: 5,
  },
  {
    id: 5,
    name: 'Lisa Park',
    role: 'VP of Engineering',
    company: 'FinanceFlow',
    image: '/testimonials/lisa.jpg',
    content: 'The DeFi protocol Amr built for us is running flawlessly with billions in TVL. His blockchain knowledge and security-first approach gave us complete confidence.',
    rating: 5,
  },
  {
    id: 6,
    name: 'David Miller',
    role: 'Course Student',
    company: 'Self-employed Developer',
    image: '/testimonials/david.jpg',
    content: 'Amr\'s Full Stack course changed my career. I went from struggling with basics to landing a senior developer role in 6 months. Best investment I ever made.',
    rating: 5,
  },
]

// Stats
export const stats = [
  { label: 'Years of Experience', value: '20+' },
  { label: 'Projects Completed', value: '500+' },
  { label: 'Students Trained', value: '10,000+' },
  { label: 'Countries Reached', value: '50+' },
  { label: 'GitHub Stars', value: '25K+' },
  { label: 'Lines of Code', value: '5M+' },
  { label: 'Happy Clients', value: '300+' },
  { label: 'Technologies Mastered', value: '100+' },
]

// FAQs
export const faqs = [
  {
    question: 'What technologies do you specialize in?',
    answer: 'I specialize in a wide range of technologies including React, Next.js, Node.js, Python, AI/ML, cloud platforms (AWS, GCP, Azure), blockchain, and more. With 20+ years of experience, I adapt to any tech stack required for your project.',
  },
  {
    question: 'How do I book a consultation?',
    answer: 'You can book a consultation through the Appointments page on this website. Select a convenient time slot, and I will confirm within 24 hours. For urgent matters, reach out via email at amr@gharib.dev.',
  },
  {
    question: 'What is your typical project timeline?',
    answer: 'Project timelines vary based on scope and complexity. A simple web application might take 2-4 weeks, while enterprise solutions can span 3-6 months. I provide detailed timelines during the initial consultation.',
  },
  {
    question: 'Do you offer ongoing support after project completion?',
    answer: 'Absolutely! I offer various support packages including maintenance, updates, and 24/7 monitoring. All projects include a complimentary 30-day support period after launch.',
  },
  {
    question: 'Are your courses suitable for beginners?',
    answer: 'I offer courses for all skill levels. Each course clearly indicates the required prerequisites. My beginner courses assume no prior knowledge, while advanced courses build on fundamental skills.',
  },
  {
    question: 'Do you work with startups?',
    answer: 'Yes! I love working with startups and offer special packages for early-stage companies. From MVP development to scaling, I help startups achieve their technical goals efficiently.',
  },
  {
    question: 'What is your approach to project management?',
    answer: 'I follow agile methodologies with regular sprint planning, daily updates, and weekly demos. You will have full visibility into progress through shared project boards and documentation.',
  },
  {
    question: 'Can you help with technical interviews preparation?',
    answer: 'Yes! My System Design and coding courses include interview preparation modules. I also offer 1-on-1 mock interview sessions for those targeting top tech companies.',
  },
]

// Appointment Types
export const appointmentTypes = [
  {
    id: 'consultation',
    name: 'General Consultation',
    duration: 30,
    price: 0,
    description: 'Free initial consultation to discuss your project or learning goals.',
  },
  {
    id: 'technical-review',
    name: 'Technical Review',
    duration: 60,
    price: 200,
    description: 'In-depth review of your code, architecture, or technical decisions.',
  },
  {
    id: 'mentoring',
    name: 'Mentoring Session',
    duration: 60,
    price: 150,
    description: 'Personal mentoring session for career guidance and skill development.',
  },
  {
    id: 'project-planning',
    name: 'Project Planning',
    duration: 90,
    price: 300,
    description: 'Detailed planning session for your upcoming project or startup.',
  },
  {
    id: 'interview-prep',
    name: 'Interview Preparation',
    duration: 60,
    price: 175,
    description: 'Mock technical interview with feedback and improvement tips.',
  },
]

// Time slots
export const timeSlots = [
  '09:00', '09:30', '10:00', '10:30', '11:00', '11:30',
  '12:00', '12:30', '13:00', '13:30', '14:00', '14:30',
  '15:00', '15:30', '16:00', '16:30', '17:00', '17:30',
]

// Categories for filtering
export const projectCategories = [
  'All',
  'Enterprise',
  'AI/ML',
  'Blockchain',
  'Healthcare',
  'E-Commerce',
  'IoT',
  'Gaming',
  'Fintech',
]

export const courseCategories = [
  'All',
  'Web Development',
  'AI & ML',
  'Architecture',
  'Mobile Development',
  'Blockchain',
  'Security',
  'DevOps',
  'Business',
]

// Blog categories
export const categories = [
  { id: 'all', name: 'All Posts' },
  { id: 'web-development', name: 'Web Development' },
  { id: 'ai-ml', name: 'AI & Machine Learning' },
  { id: 'cloud', name: 'Cloud & DevOps' },
  { id: 'career', name: 'Career & Growth' },
  { id: 'tutorials', name: 'Tutorials' },
  { id: 'news', name: 'Tech News' },
]

// Blog posts
export const blogPosts = [
  {
    id: '1',
    slug: 'building-scalable-microservices',
    title: 'Building Scalable Microservices with Node.js and Kubernetes',
    excerpt: 'Learn how to design and deploy production-ready microservices architecture.',
    content: '',
    image: '/images/blog/microservices.jpg',
    category: 'cloud',
    author: 'Amr Gharib',
    publishedAt: '2025-01-15',
    readTime: 12,
    featured: true,
    tags: ['microservices', 'kubernetes', 'nodejs', 'docker'],
  },
  {
    id: '2',
    slug: 'ai-powered-web-applications',
    title: 'Building AI-Powered Web Applications with Next.js and OpenAI',
    excerpt: 'Integrate cutting-edge AI capabilities into your web applications.',
    content: '',
    image: '/images/blog/ai-web.jpg',
    category: 'ai-ml',
    author: 'Amr Gharib',
    publishedAt: '2025-01-10',
    readTime: 15,
    featured: true,
    tags: ['ai', 'openai', 'nextjs', 'chatgpt'],
  },
  {
    id: '3',
    slug: 'mastering-react-performance',
    title: 'Mastering React Performance: Tips and Best Practices',
    excerpt: 'Optimize your React applications for lightning-fast performance.',
    content: '',
    image: '/images/blog/react-performance.jpg',
    category: 'web-development',
    author: 'Amr Gharib',
    publishedAt: '2025-01-05',
    readTime: 10,
    featured: false,
    tags: ['react', 'performance', 'optimization', 'frontend'],
  },
]
